# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 307)
        Dialog.setMinimumSize(QtCore.QSize(402, 307))
        Dialog.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(50, -1, 50, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 3)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 3)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 3)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setStyleSheet("font: 10pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 2, 1, 1)

        self.retranslateUi(Dialog)
        #self.pushButton.clicked.connect(Dialog.new_message) # type: ignore
        self.pushButton.clicked.connect(Dialog.Modify_Message) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "姓名："))
        self.label_11.setText(_translate("Dialog", "科室："))
        self.label_12.setText(_translate("Dialog", "医院："))
        self.label_13.setText(_translate("Dialog", "性别："))
        self.pushButton.setText(_translate("Dialog", "确认修改"))
