# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtuntitled1_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(464, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(464, 316))
        Form.setSizeIncrement(QtCore.QSize(0, 0))
        Form.setStyleSheet("color:rbg(255,255,255)")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 461, 311))
        self.frame.setStyleSheet("QFrame{ border-radius:30px;\n"
" }\n"
"   ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 172, 331, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:10px;\n"
"    margin-left:15px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(20)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(261, 250, 111, 21))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    height:25px;\n"
"    border-radius:10px;\n"
"    font-family:\\\'Arial\\\';\n"
"    font-size:15px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
"\n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
"  }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(70, 102, 331, 51))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:10px;\n"
"    margin-left:15px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(101, 250, 111, 21))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    height:25px;\n"
"    border-radius:10px;\n"
"    font-family:\\\'Arial\\\';\n"
"    font-size:15px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
"\n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
"  }")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(83, 40, 301, 50))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setToolTip("")
        self.label_3.setStyleSheet("QLabel{\n"
" color:rgb(0,0,0);\n"
"    border:0px;\n"
"    text-align:right;\n"
"    font-family:\\\'微软雅黑\\\';\n"
"    font-size:25px;\n"
"    \n"
"  border-image: url(); \n"
"background-color:rgba(0,0,0,0);\n"
" }\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(359, 10, 41, 21))
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 15))
        self.pushButton_3.setStyleSheet("QPushButton { \n"
"font: 75 11pt \"黑体\";\n"
"\n"
"background-color:rgb(255, 0, 0,0);\n"
"}\n"
" QPushButton:hover { \n"
"background-color:rgb(255, 0, 0);\n"
" }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 10, 31, 21))
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 15))
        self.pushButton_4.setStyleSheet("QPushButton { \n"
"font: 75 11pt \"黑体\";\n"
"\n"
"background-color:rgb(255, 0, 0,0);\n"
"}\n"
" QPushButton:hover { \n"
"background-color:rgb(255, 0, 0);\n"
" }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.log_in)
        self.pushButton_2.clicked.connect(Form.register_1)
        self.pushButton_3.clicked.connect(Form.slot1)
        self.pushButton_4.clicked.connect(Form.slot2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "密码："))
        self.pushButton_2.setText(_translate("Form", "注册"))
        self.lineEdit.setPlaceholderText(_translate("Form", "账号："))
        self.pushButton.setText(_translate("Form", "登录"))
        self.label_3.setText(_translate("Form", "肺结核空洞检测平台"))
        self.pushButton_3.setText(_translate("Form", "-"))
        self.pushButton_4.setText(_translate("Form", "×"))
import background_rc
