# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtuntitled4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 339)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 111, 91))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 130, 291, 21))
        self.label_9.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(30, 170, 281, 21))
        self.label_10.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(330, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 140, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 220, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(30, 210, 291, 21))
        self.label_11.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 250, 291, 21))
        self.label_12.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(30, 290, 261, 21))
        self.label_13.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.change_head) # type: ignore
        self.pushButton_2.clicked.connect(Form.message) # type: ignore
        self.pushButton.clicked.connect(Form.changepassword) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "用户名："))
        self.label_10.setText(_translate("Form", "姓名："))
        self.pushButton.setText(_translate("Form", "密码修改"))
        self.pushButton_2.setText(_translate("Form", "信息修改"))
        self.pushButton_3.setText(_translate("Form", "更改头像"))
        self.label_11.setText(_translate("Form", "科室："))
        self.label_12.setText(_translate("Form", "医院："))
        self.label_13.setText(_translate("Form", "性别："))
