# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtuntitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(464, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(464, 316))
        Form.setSizeIncrement(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(50, 20, 30, 20)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(28)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setStyleSheet("font: 14pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:10px;\n"
"    margin-left:15px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:10px;\n"
"    margin-left:15px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    height:25px;\n"
"    border-radius:10px;\n"
"    font-family:\\\'Arial\\\';\n"
"    font-size:15px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
"\n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
"  }")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Arial\\\';\n"
"    font-size:25px;\n"
"    font-weight:bold;   \n"
" }\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setStyleSheet("font: 14pt \"Arial\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    height:25px;\n"
"    border-radius:10px;\n"
"    font-family:\\\'Arial\\\';\n"
"    font-size:15px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
"\n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
"  }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(Form.register) # type: ignore
        self.pushButton.clicked.connect(Form.log_in) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "密码"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.label_3.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">学生登录界面</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "肺结核空洞检测平台"))
        self.label_2.setText(_translate("Form", "账号"))
        self.pushButton_2.setText(_translate("Form", "注册"))
