# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtuntitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(383, 391)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(300, 297))
        Form.setMaximumSize(QtCore.QSize(600, 600))
        self.formWidget = QtWidgets.QWidget(Form)
        self.formWidget.setGeometry(QtCore.QRect(20, 70, 331, 231))
        self.formWidget.setObjectName("formWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:5px;\n"
"    margin-left:10px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:5px;\n"
"    margin-left:10px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:5px;\n"
"    margin-left:10px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(self.formWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    border:0px;\n"
"    margin:5px;\n"
"    margin-left:10px;\n"
"    margin-right:15px;\n"
"    border-bottom: 2px solid #B3B3B3;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:15px; \n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;\n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;\n"
"    }\n"
"\n"
"QWidget#centralwidget{\n"
"    background:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    text-align:right;\n"
"    font-family:\\\'Microsoft YaHei\\\';\n"
"    font-size:30px;\n"
"    font-weight:bold;\n"
"    }\n"
"\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 320, 91, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    height:25px;\n"
"    border-radius:10px;\n"
"    font-family:\\\'Arial\\\';\n"
"    font-size:15px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
"\n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
"  }border:2px groove gray;border-radius:10px;padding:6px 12px;")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 19, 151, 31))
        self.label_5.setStyleSheet("font: 75 14pt \"Microsoft JhengHei\";\n"
"font: 75 9pt \"Arial\";\n"
"font: 75 14pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.pushButton.clicked.connect(self.register)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "用户名"))
        self.label_2.setText(_translate("Form", "密码"))
        self.label_3.setText(_translate("Form", "确认密码"))
        self.label_4.setText(_translate("Form", "性别"))
        self.pushButton.setText(_translate("Form", "注册"))
        self.label_5.setText(_translate("Form", "欢迎注册"))
